#!/usr/bin/env bash
# script to transfer a file from our client to a server

# check that 4 arguments have been provided
if [ $# -ne 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file_path=$1
	server_ip=$2
	username=$3
	ssh_key_path=$4

	scp -i "$ssh_key_path" -o "User=$username" "$file_path" "$username@$server_ip:~/"
fi
