#!/usr/bin/env bash
# Installs Nginx on server web-01

# Update the package index
sudo apt-get update

## Install Nginx
sudo apt-get install nginx -y

# Create Hello World page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
