#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page that contains the string `Ceci n'est pas une page` and a custom response header

sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname of the server
hostname=$(hostname)

# Create Hello World page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Define the custom 404 error page and add a custom response header
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html


# Use sed to modify the Nginx configuration file
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/BrianEtemesi permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default


sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$hostname\";/" /etc/nginx/nginx.conf

# Reload Nginx to apply the changes
sudo service nginx restart
