#!/usr/bin/env bash
# install and configure HAproxy to send traffic to 100.25.137.152 and 35.168.1.108

# Install HAproxy
sudo apt-get update
sudo apt-get install haproxy

# configure HAproxy to send traffic to server 1 and 2 using round robin algorithm

configFrontend='''
frontend myFrontend
        bind :80
        default_backend myBackend
'''

# save backend config in a variable
configBackend='''
backend myBackend
        balance roundrobin
        server 116170-web-01 100.25.137.152:80 check
        server 116170-web-02 35.168.1.108:80 check
'''

# configure HAproxy
cat <<EOF >> /etc/haproxy/haproxy.cfg
$configFrontend
$configBackend
EOF

# enable HAproxy to be started by an init script
# echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# restart HAproxy to apply changes
sudo service haproxy restart

# sudo /etc/init.d/haproxy start
# sudo update-rc.d haproxy defaults
# sudo /etc/init.d/haproxy reload
