#!/usr/bin/env bash
# install and configure HAproxy to send traffic to 100.25.137.152 and 35.168.1.108

# Install HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# configure HAproxy to send traffic to server 1 and 2 using round robin algorithm
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 116170-web-01 100.25.137.152:80 check\n\tserver 116170-web-02 35.168.1.108:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# restart HAproxy to apply changes
sudo service haproxy restart
