#!/usr/bin/env bash
# Script to configure nginx to listen on port 80

# delete sites-enabled configuration file
rm /etc/nginx/sites-enabled/default

# create symbolic link from sites-available file
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx to apply changes
sudo service nginx restart
