#!/usr/bin/env bash
# configure nginx to listen on port 80; status to be 'nginx not running' after running script
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
