#!/usr/bin/env bash
#This scripts prints numbers 1 to 100
#displays FizzBuzz when number is a multiple of 3 and 5
#displays Fizz for multiples of 3
#displays Buzz for multiples of 5

for i in {1..100}
do
	if [ $((i%15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i%5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i%3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
