#!/usr/bin/env bash
#This script prints "Best School" 10 times
#prints "Hi" instead of "Best School" at the 9th iteration

x=0
while [ $x -lt 10 ]
do
	if [ $x -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	x=$(( x + 1 ))
done
