#!/usr/bin/env bash
#This script loops from 1 to 10
#displays 'bad luck' for the 4 loop iteration
#displays 'good luck' for the 8 loop iteration
#displays 'Best School' for other iterations

x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	x=$(( x + 1 ))
done
