#!/usr/bin/env bash
#This bash script displays the time for 12 hours and 55 minutes

i=0
while [ $i -le 12 ]
do
	echo "Hour: $i"
	x=0
	while [ $x -lt 60 ]
	do
		echo "$x"
		x=$(( x + 1 ))
	done
	i=$(( i + 1 ))
done
